add debugging do dist

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,6 +34,14 @@ jobs:
           script: |
             rm -rf /home/ubuntu/bukabuku/docker/app/wp-content/themes/mytheme/dist/*
 
+      - name: Debug build output
+          run: |
+            echo "=== FRONTEND FOLDER ==="
+            ls -la frontend
+
+            echo "=== DIST FOLDER ==="
+            ls -la frontend/dist || echo "dist not found"
+
       - name: Copy frontend build to EC2
         uses: appleboy/scp-action@v0.1.7
         with:
